docs: add local development guide
rik-org/rik pull request #28
Opened 2023-01-26 15:36 UTC by hugoamalric

Add local development guide to launch a rik cluster

2023-01-26 15:46 UTC, MaloPolese requested changes

2023-01-26 15:46 UTC, MaloPolese commented on CONTRIBUTING.md
> +sudo apt install -y umoci skopeo runc protobuf-compiler
Can you add the equivalent for Fedora ?

```
curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip

unzip protoc-3.21.12-linux-x86_64 -d $HOME/.local

export PATH="$PATH:$HOME/.local/bin"
```

2023-01-26 15:46 UTC, MaloPolese commented on README.md
> +- Ubuntu: `sudo apt update && sudo apt install libssl-dev`
- Fedora: `sudo dnf update && sudo dnf install openssl-devel`

2023-01-26 15:47 UTC, mflagey commented on README.md
> +- Ubuntu: `sudo apt update && sudo apt install libssl-dev`
Don't delete protobuf-compiler

2023-03-14 16:13 UTC, thomasgouveia approved these changes

2023-03-14 16:20 UTC, MaloPolese approved these changes

2023-03-14 16:29 UTC, merged