fix: repair logs in riklet
rik-org/rik pull request #44
Opened 2023-03-15 15:41 UTC by mflagey

closes #43

2023-03-15 16:11 UTC, hugoamalric requested changes

2023-03-15 16:11 UTC, hugoamalric commented on riklet/src/main.rs
> +        )
This should be configurable according to the verbosity level

2023-03-16 15:40 UTC, MaloPolese approved these changes

2023-03-16 15:42 UTC, hugoamalric approved these changes

2023-03-16 15:42 UTC, merged